{% set version = "2.2.2" %}

package:
  name: sedflux
  version: {{ version }}

source:
  url: https://github.com/mcflugen/sedflux/archive/v{{ version }}.tar.gz
  sha256: 44486fed37f9d021075014186b79984cd9ab60e301016734d40e372dcc49b868

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
  host:
    - glib
  run:
    - glib

test:
  commands:
    - sedflux -h

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A stratigraphic basin-filling model
  description: |
    Sedflux-2.0 is the newest version of the Sedflux basin-filling
    model. Sedflux-2.0 provides a framework within which individual
    process-response models of disparate time and space resolutions
    communicate with one another to deliver multi grain sized
    sediment load across a continental margin.
  doc_url: http://sedflux.readthedocs.io/
  dev_url: http://github.com/mcflugen/sedflux

extra:
  recipe-maintainers:
    - mcflugen
